RangerTrainingAuth/Entities/KalenderEintrag.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RangerTrainingAuth.Entities
{
    [DebuggerDisplay("{Anlass} ({Date} - {EndDate})")]
    public class KalenderEintrag
    {
        public int ID { get; set; }
        public int Gruppe { get; set; }
        public bool AlleGruppen { get; set; }
        public String Bezeichnung { get; set; }  
        public DateTime Date { get; set; } 
        public DateTime EndDate { get; set; }  
        public string Anlass { get; set; }  
        public bool SerienTermin { get; set; }
        public Guid SerienNummer { get; set; }

        internal KalenderEintrag Copy()
        {
            KalenderEintrag ke = new KalenderEintrag();

            ke.ID = ID;
            ke.Gruppe = Gruppe;
            ke.Bezeichnung = Bezeichnung;
            ke.Date = Date;
            ke.EndDate = EndDate;
            ke.Anlass = Anlass;
            ke.SerienTermin = SerienTermin;
            ke.SerienNummer = SerienNummer;

            return ke;
        }
    }
}

RangerTrainingAuth/Models/KalenderEintrag/KalenderEintragModel.cs
using RangerTrainingAuth.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RangerTrainingAuth.Models.KalenderEintrag
{
    public class KalenderEintragModel
    {
        public String Bezeichnung { get; set; }
        public DateTime Date { get; set; } = DateTime.Now;
        public DateTime EndDate { get; set; } = DateTime.Now;
        public TimeSpan Startzeit { get; set; } 
        public TimeSpan EndZeit { get; set; }

        public string Anlass { get; set; } = KalenderEventNamen.Training;
        public bool SerienTermin { get; set; } = false;
        public int SerienTerminType { get; set; } 
        public int SerienTerminTagesAbstand { get; set; } = 0;
        public bool AlleGruppen { get; set; } = true;
        public bool Gruppe1 { get; set; } = false;
        public bool Gruppe2 { get; set; } = false;
        public bool Gruppe3 { get; set; } = false;
        public bool Gruppe4 { get; set; } = false;
        public bool Gruppe5 { get; set; } = false;

    }
}

RangerTrainingAuth/Controllers/KalenderEintragController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RangerTrainingAuth.Data;
using RangerTrainingAuth.Models.KalenderEintrag;
using RangerTrainingAuth.Services;

namespace RangerTrainingAuth.Controllers
{
    [Authorize(Roles = Rolename.Admin)]
    public class KalenderEintragController : Controller
    {
        private KalenderEintragsService _kalenderEintragsService;

        public KalenderEintragController(KalenderEintragsService kalenderEintragsService)
        {
            _kalenderEintragsService = kalenderEintragsService ?? throw new ArgumentNullException(nameof(kalenderEintragsService));
        }

        public IActionResult Index()
        {
            return View(new   KalenderEintragModel());
        }

        [HttpGet]
        public IActionResult Delete([FromQuery]int id)
        {
            var eintrag = _kalenderEintragsService.Get(id);

            if (eintrag == null)
            {
                return NotFound();
            }
            else
            {
                return View(eintrag);
            }
        }

        [HttpPost]
        public IActionResult DeleteEintrag([FromForm]int id)
        {
            var eintrag = _kalenderEintragsService.Get(id);

            if (eintrag == null)
            {
                return NotFound();
            }
            else
            {
                _kalenderEintragsService.Delete(id);

                return RedirectToAction("Index", "Kalender");
            }
        }

        [HttpPost]
        public IActionResult DeleteSerienEintrag([FromForm]int id, [FromForm]int clearType)
        {
            var eintrag = _kalenderEintragsService.Get(id);

           

            if (eintrag == null)
            {
                return NotFound();
            }
            else if(clearType == 1)
            {
            
                _kalenderEintragsService.DeleteSerie(id);

                return RedirectToAction("Index", "Kalender");
            }
            return BadRequest();


        }

        [HttpPost]
        public async Task<IActionResult> KalendereintragUebernahme([FromForm]KalenderEintragModel KalenderEintragModel)
        {

           await _kalenderEintragsService.Set(KalenderEintragModel);

            return View();
        }

    }
}

RangerTrainingAuth/Views/KalenderEintrag/Delete.cshtml
@model RangerTrainingAuth.Entities.KalenderEintrag
@{
    ViewData["Title"] = "Kalendereintrag löschen";
}

<h1>Kalendereintrag löschen</h1>



@if (Model.SerienTermin == false)
{

    <p>
        Möchten Sie den Kalendereintrag "@Model.Bezeichnung" wirklich löschen?
    </p>



    <form method="post" asp-controller="KalenderEintrag" asp-action="DeleteEintrag">
        <button type="submit" class="btn btn-success">Ja</button>
        <input type="hidden" asp-for="@Model.ID" />
        <!-- Nein-->
        <a asp-action="Index" asp-controller="Kalender" class="btn btn-danger">Nein</a>
    </form>

}
else
{

    <p>
        Möchten Sie den Serieneintrag "@Model.Bezeichnung" wirklich löschen?
    </p>



    <form method="post" asp-controller="KalenderEintrag" asp-action="DeleteSerienEintrag">
        <button type="submit" class="btn btn-success">Serie löschen</button>
        <input type="hidden" asp-for="@Model.ID"  />
        <input type="hidden" name="ClearType" value="1"/>
 
    </form>
    <form method="post" asp-controller="KalenderEintrag" asp-action="DeleteEintrag">
        <button type="submit" class="btn btn-success">Nur diesen Eintrag löschen</button>

        <input type="hidden" asp-for="@Model.ID" />
        <a asp-action="Index" asp-controller="Kalender" class="btn btn-danger">Abbruch</a>
    </form>


}

RangerTrainingAuth/Views/KalenderEintrag/Index.cshtml
@model RangerTrainingAuth.Models.KalenderEintrag.KalenderEintragModel
@using RangerTrainingAuth.Models.KalenderEintrag
@using RangerTrainingAuth.Data



    <form asp-controller="KalenderEintrag" asp-action="KalendereintragUebernahme" method="post">

        <div asp-validation-summary="All" class="text-danger"></div>

        <h1>Kalender Eintrag</h1>

        <h1> </h1>



        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Bezeichnung</label>
            <div class="col-sm-6">
                <input type="text" class="form-control" id="@Model.Bezeichnung" asp-for="@Model.Bezeichnung" required>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Ereignistype</label>
            <div class="col-sm-6">
                <input type="search" list="eventtype" class="form-control" id="Anlass" asp-for="@Model.Anlass" required>
            </div>
        </div>
        <datalist id="eventtype">
            <option value=@KalenderEventNamen.Training style="background-color: aqua" />
            <option value=@KalenderEventNamen.FlexTraining style="background-color: aqua" />
            <option value=@KalenderEventNamen.Heimspiel />
            <option value=@KalenderEventNamen.Auswertsspiel />
            <option value=@KalenderEventNamen.Teamsitzung />
            <option value=@KalenderEventNamen.Geburtstag />
            <option value=@KalenderEventNamen.Sonstiges />
            <option value=@KalenderEventNamen.SaisonStart />
            <option value=@KalenderEventNamen.SaisonEnde />
        </datalist>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Datum</label>
            <div class="col-sm-3">
                <input type="date" class="form-control" id="StartDatum" asp-for="@Model.Date ">
            </div>

            <label class="col-sm-1 col-form-label">von </label>
            <div class="col-sm-2">
                <input type="time" class="form-control" td id=" @Model.Startzeit    " asp-for="@Model.Startzeit ">
            </div>

        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Enddatum</label>
            <div class="col-sm-3">
                <input type="date" class="form-control" id="EndDatum" asp-for="@Model.EndDate ">
            </div>
            <label class="col-sm-1 col-form-label">bis </label>
            <div class="col-sm-2">
                <input type="time" class="form-control" asp-for="@Model.EndZeit ">
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-2">Gruppen</div>
            <div class="col-sm-1">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="alleGruppenCheckbox" asp-for="@Model.AlleGruppen ">alle

                </div>
            </div>

            <div class="col-sm-1">
                <div class="form-check">
                    <input class="form-check-input gruppen-checkbox" type="checkbox" asp-for="@Model.Gruppe1" />1

                </div>
            </div>
            <div class="col-sm-1">
                <div class="form-check">
                    <input class="form-check-input gruppen-checkbox" type="checkbox" asp-for="@Model.Gruppe2" />2

                </div>
            </div>
            <div class="col-sm-1">
                <div class="form-check">
                    <input class="form-check-input gruppen-checkbox" type="checkbox" asp-for="@Model.Gruppe3" />3

                </div>
            </div>
            <div class="col-sm-1">
                <div class="form-check">
                    <input class="form-check-input gruppen-checkbox" type="checkbox" asp-for="@Model.Gruppe4" />4

                </div>
            </div>
            <div class="col-sm-1">
                <div class="form-check">
                    <input class="form-check-input gruppen-checkbox" type="checkbox" asp-for="@Model.Gruppe5" />5

                </div>
            </div>

        </div>

        <div class="form-group row">
            <div class="col-sm-2">Serientermin</div>
            <div class="col-sm-10">
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id=" @Model.SerienTermin" asp-for="@Model.SerienTermin ">

                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-2">Periode</div>
            <div class="col-sm-10">
                <fieldset class="form-group">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="SerienTerminType" id="gridRadios1" value="1" checked>
                                <label class="form-check-label" for="gridRadios1">
                                    wöchentlich
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="SerienTerminType" id="gridRadios2" value="2">
                                <label class="form-check-label" for="gridRadios2">
                                    alle 4 Wochen
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="SerienTerminType" id="gridRadios3" value="3">
                                <label class="form-check-label" for="gridRadios3">
                                    alle <input type="number" id="@Model.SerienTerminTagesAbstand" asp-for="@Model.SerienTerminTagesAbstand" maxlength="4" min="0" max="30" Tage />
                                    Tage
                                </label>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>

        <div class="form-group row">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-primary">Eintragen</button>
            </div>
        </div>

 
    </form>

@section Scripts {
   
         @* src=" ~ == wwwroot*@
    <script src="~/js/kalender-eintrag.js"></script>
}

RangerTrainingAuth/Views/KalenderEintrag/KalendereintragUebernahme.cshtml
@{
    ViewData["Title"] = "KalendereintragUebernahme";
}

<h1>KalendereintragUebernahme</h1>