RangerTrainingAuth/Controllers/ClearUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RangerTrainingAuth.Models.ClearUser;
using RangerTrainingAuth.Services;

namespace RangerTrainingAuth.Controllers
{
    public class ClearUserController : Controller
    {
        private readonly UserService userService;

        public ClearUserController(UserService userService)
        {
            this.userService = userService ?? throw new ArgumentNullException(nameof(userService));
        }

        // GET: ClearUser
        public ActionResult Index()
        {
             ClearUserViewModel vi = new  ClearUserViewModel();
            vi.UserToClearListe = userService.GetUserToClear();
            return View(vi );
        }

        // GET: ClearUser/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClearUser/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClearUser/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ClearUser/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClearUser/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        


        // POST: ClearUser/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(ClearUserViewModel collection)
        {
            if (collection is null)
            {
                throw new ArgumentNullException(nameof(collection));
            }

            var count = collection.UserToClearListe.Where(u => u.Selected).Count();

            if(count ==1)
            {
                UserToClear selectetUser = collection.UserToClearListe.FirstOrDefault(u => u.Selected);



                if(selectetUser!= null && selectetUser.Name == "Georg Zwirkowski")
                {
                   // await userService.ClearAllUserAsync().ConfigureAwait(false);
                    return View();
                }
            }


            try
            {
               for( int i=0; i< collection.UserToClearListe.Count;i++)
                {
                    if (collection.UserToClearListe[i].Selected)
                    {
                      await  userService.ClearUserAsync(collection.UserToClearListe[i].Name).ConfigureAwait(false);
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

RangerTrainingAuth/Controllers/ErgebnisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RangerTrainingAuth.Models.Ergebnis;
using RangerTrainingAuth.Services;

namespace RangerTrainingAuth.Controllers
{
    public class ErgebnisController : Controller
    {

        public ErgebnisController(ErgebnisService ergebnisService)
        {
            ErgebnisService = ergebnisService ?? throw new ArgumentNullException(nameof(ergebnisService));
        }

        public ErgebnisService ErgebnisService { get; }

        public IActionResult Index()
        {

            IndexErgebnisViewModel viewmodel = new IndexErgebnisViewModel();
            viewmodel =   ErgebnisService.GetErgebnisse();
            return View(viewmodel);
        }
    }
}

RangerTrainingAuth/Controllers/KalenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RangerTrainingAuth.Models.Kalender;
using RangerTrainingAuth.Services;

namespace RangerTrainingAuth.Controllers
{
    public class KalenderController : Controller
    {
        private readonly KalenderEintragsService kalenderEintragsService;

        public KalenderController(KalenderEintragsService kalenderEintragsService)
        {
            this.kalenderEintragsService = kalenderEintragsService ?? throw new ArgumentNullException(nameof(kalenderEintragsService));
        }

        public IActionResult Index()
        {
            return View();
        }

        public Event[] Events()
        {

            return kalenderEintragsService.GetEvents();

            //return new Event[]
            //{
            //    new Event
            //    {
            //        ID = Guid.NewGuid().ToString(),
            //        Title = "Testeintrag",
            //        Start = DateTime.Now,
            //        End = DateTime.Now + TimeSpan.FromHours(4),
            //        BackgroundColor = "#f00000",
            //        TextColor="#000000"
            //    },
            //    new Event
            //    {
            //        ID = Guid.NewGuid().ToString(),
            //        Title = "Training im Forest",
            //        Start = DateTime.Now + TimeSpan.FromDays(1.5),
            //        End = DateTime.Now + TimeSpan.FromDays(3.7),
            //        BackgroundColor = "#0f00f0",
            //        TextColor="#ffff00"

            //    }
            //};
        }
    }
}

RangerTrainingAuth/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RangerTrainingAuth.Models.User;
using RangerTrainingAuth.Services;

namespace RangerTrainingAuth.Controllers
{
    public class UserController : Controller
    {
        public UserController(UserService userService)
        {
            if (userService == null)
                throw new ArgumentNullException(nameof(userService));
            UserService = userService;
        }

        public UserService UserService { get; }



        // GET: User
        public ActionResult Index(string namenfilter = null)
        {
            UserViewModel vi = new UserViewModel();
            vi.UserListe = UserService.GetUserListe(namenfilter);

            return View(vi);
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        //[HttpGet("Edit/{id}")]
        [HttpGet("[controller]/{id}/Edit")]
        public ActionResult EditUser(string id)
        {
            EditUserViewModel vi = new EditUserViewModel();
            vi = UserService.GetUserDaten(id);

            return View(vi);
        }




        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UebernahmeUser(EditUserViewModel userdaten)
        {
            UserService.SetUserDaten(userdaten);
            return View();
        }


        // POST: User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

RangerTrainingAuth/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using RangerTrainingAuth.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link href='~/lib/fullcalendar/core/main.css' rel='stylesheet' />
    <link href='~/lib/fullcalendar/daygrid/main.css' rel='stylesheet' />
    <script src='~/lib/fullcalendar/core/main.js'></script>
    <script src='~/lib/fullcalendar/core/locales/de.js'></script>
    <script src='~/lib/fullcalendar/daygrid/main.js'></script>

    <title>@ViewData["Title"] - Ranger Trainingszeit Erfassung</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ranger Training</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@


                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="false" aria-expanded="false"> <span class="nav-link text-dark">Gruppen</span>  </a>
                            <ul class="dropdown-menu">



                                @if (SignInManager.IsSignedIn(User) && (User?.IsInRole(Rolename.Gruppenleiter) ?? false))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Spielerauswahl" asp-action="Index">SpielerAuswahl</a>
                                    </li>
                                }

                                @if (SignInManager.IsSignedIn(User) && (User?.IsInRole(Rolename.Admin) ?? false))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="GruppenLeiterAuswahl" asp-action="Index">Gruppenleiterauswahl</a>
                                    </li>
                                }
                                @if (SignInManager.IsSignedIn(User) && (User?.IsInRole(Rolename.Admin) ?? false))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User bearbeiten</a>
                                    </li>
                                }
                                @if (SignInManager.IsSignedIn(User) && (User?.IsInRole(Rolename.Admin) ?? false))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="ClearUser" asp-action="Index">User löschen</a>
                                    </li>
                                }

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="GruppenUebersicht" asp-action="Index">Gruppenübersicht</a>
                                </li>

                            </ul>






                            @if (SignInManager.IsSignedIn(User) && (User?.IsInRole(Rolename.Gruppenleiter) ?? false))
                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TrainingsTeilnahme" asp-action="Index">Trainings Teilnahme</a>
                            </li>
                        }

                            @if (SignInManager.IsSignedIn(User) && (User?.IsInRole(Rolename.Admin) ?? false))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Steuerung" asp-action="Index">Steuerung</a>
                                </li>
                            }


                            @if (SignInManager.IsSignedIn(User) && (User?.IsInRole(Rolename.Admin) ?? false))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ClearAllUser" asp-action="Index">Alle User Löschen</a>
                                </li>
                            }


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ergebnis" asp-action="Index">Ergebnis</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Übersicht" asp-action="Index">Übersicht</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Kalender" asp-action="Index">Kalender</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="KalenderEintrag" asp-action="Index">KalenderEintrag</a>
                            </li>

                        </ul>
                        </div>
                    </div>
                </nav>
            </header>
            <div class="container">
                <partial name="_CookieConsentPartial" />
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2019 - RangerTraining - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>

            <environment include="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
            </environment>
            <environment exclude="Development">
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
                </script>
                <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
                </script>
            </environment>
            <script src="~/js/site.js" asp-append-version="true"></script>

            @RenderSection("Scripts", required: false)
        </body>
        </html>
        @*<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Services</span> <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="#">Service A</a></li>
                <li><a href="#">Service B</a></li>
                <li class="dropdown-submenu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="nav-label">Service C</span><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Service C1</a></li>
                        <li><a href="#">Service C2</a></li>
                        <li><a href="#">Service C3</a></li>
                        <li><a href="#">Service C4</a></li>
                        <li><a href="#">Service C5</a></li>
                    </ul>
                </li>
            </ul>
        </li>*@