RangerTrainingAuth/Models/TrainingsTeilnahme/TrainingsTeilnahmeModel.cs
using RangerTrainingAuth.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RangerTrainingAuth.Models.TrainingsTeilnahme
{
    public class TrainingsTeilnahmeModel
    {
        [Required, MaxLength(40), MinLength(4)]
        public string TrainingstagString { get; set; }
        public DateTime? Trainingstag { get; set; }
        public DateTime SaisonStart { get; set; }
        public string SaisonStartString => SaisonStart.ToString("dd.MM.yyyy");
        public DateTime SaisonEnde { get; set; }
        public string SaisonEndeString => SaisonEnde.ToString("dd.MM.yyyy");
        // public int TrainingsGruppe { get; set; }
        public DateTime[] Trainingstage { get; set; }

        public SpielerImTraining[] SpielerImTrainings { get; set; }
    }
}

RangerTrainingAuth/Controllers/TrainingsTeilnahmeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RangerTrainingAuth.Models.TrainingsTeilnahme;
using RangerTrainingAuth.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace RangerTrainingAuth.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class TrainingsTeilnahmeController : Controller
    {
        private readonly TrainingsTeilnahmeService trainingsTeilnahmeService;

        public TrainingsTeilnahmeController(TrainingsTeilnahmeService trainingsTeilnahmeService)
        {
            if (trainingsTeilnahmeService == null)
                throw new ArgumentNullException(nameof(trainingsTeilnahmeService));

            this.trainingsTeilnahmeService = trainingsTeilnahmeService;
        }



        public async Task<IActionResult> Index(DateTime? datum = null)
        {

           
            TrainingsTeilnahmeModel viewmodel = await trainingsTeilnahmeService.GetAsync(datum, User);


            return View(viewmodel);
        }

        [HttpPost]
        public async Task<IActionResult> UebernahmeTeilnahmeImTraining([FromForm]TrainingsTeilnahmeModel submitModel)
        {
            if (ModelState.IsValid)
            {

            }

            await trainingsTeilnahmeService.SetTeilnahmeAsync(submitModel);


            return View();
        }
    }
}

RangerTrainingAuth/Views/TrainingsTeilnahme/Index.cshtml
@model RangerTrainingAuth.Models.TrainingsTeilnahme.TrainingsTeilnahmeModel
@using RangerTrainingAuth.Models.TrainingsTeilnahme
<h1> Trainingsteilnahme</h1>

<form asp-controller="TrainingsTeilnahme" asp-action="UebernahmeTeilnahmeImTraining" method="post">

    <div asp-validation-summary="All" class="text-danger"></div>

    <p>Saison vom @Model.SaisonStartString bis @Model.SaisonEndeString</p>
    <div>
        <select id="Selectindex">
            <option>@Model.TrainingstagString</option>

            @foreach (DateTime tag in Model.Trainingstage)
            {
                <option value="@tag.ToString("s", System.Globalization.CultureInfo.InvariantCulture)">@tag.ToString("dd.MM.yyyy")</option>
                @*<option value="@tag.ToString("dd/MM/yyyy")"></option>*@
            }
        </select>
    </div>



    <div asp-validation-summary="All" class="text-danger"></div>

    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Gruppe</th>
                <th scope="col">Name</th>
                <th scope="col">Teilnahme</th>
            </tr>
        </thead>

        <tbody> 
            @if (Model.SpielerImTrainings != null)
            {

                <input type="hidden" name="TrainingstagString" value="@Model.TrainingstagString"/>

                @for (int i = 0; i < Model.SpielerImTrainings.Count(); i++)
                {


                    <tr>

                        <td>@Model.SpielerImTrainings[i].Gruppe </td>
                        <td>@Model.SpielerImTrainings[i].Spieler.Name    </td>
                        <td>
                            <input type="checkbox" id="@Model.SpielerImTrainings[i].Spieler.Name" asp-for="@Model.SpielerImTrainings[i].Anwesend" disabled="@Model.SpielerImTrainings[i].Eneabled" />
                            <input type="hidden" asp-for="@Model.SpielerImTrainings[i].Spieler.Vorname" />
                            <input type="hidden" asp-for="@Model.SpielerImTrainings[i].Spieler.Nachname" />
                            <input type="hidden" asp-for="@Model.Trainingstag" />
                            <input type="hidden" asp-for="@Model.SpielerImTrainings[i].Eneabled" />
                        </td>


                    </tr>

                }



            }
        </tbody>
    </table>
    <button type="submit">Übernehmen</button>
</form>

    <script>
        const selectobject = document.getElementById("Selectindex");
        selectobject.addEventListener("change", function (event) {
            const selectedOption = event.target.selectedOptions[0].value;

            if (selectedOption) {
                window.location.search = `?datum=${selectedOption}`;
            }
        });
    </script>

RangerTrainingAuth/Views/TrainingsTeilnahme/TrainigingsTeilnahme.cshtml
@{
    ViewData["Title"] = "TrainigingsTeilnahme";
}

    <div class="alert-success">
        <strong>Erfolg!</strong>

        <p>Die Auswahl wurde übernommen.</p>
    </div>

RangerTrainingAuth/Views/TrainingsTeilnahme/UebernahmeTeilnahmeImTraining.cshtml
@{
    ViewData["Title"] = "UebernahmeTeilnahmeImTraining";
}

<div class="alert-success">
    <strong>Erfolg!</strong>

    <p>Die Auswahl wurde übernommen.</p>
</div>